# Generated by Django 5.0.3 on 2024-03-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='text')),
            ],
        ),
        migrations.CreateModel(
            name='VectorDataset',
            fields=[
                ('original_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('vector_data', models.TextField()),
            ],
        ),
    ]
